# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 240543ad7557245f4aa14fcfbc3806504d0e24683e8a34fddcb61d9ea17a14052265d8d63e7a3f9947b7cdc6f93e35cf9103ac94cfabd0db00472884f65702c6

test:
  secret_key_base: d5c87dd6e9519f5dc8fa263c66f7194bc3cc8d186e52f0076b4e1c910a74b43aa9d7a499ec6f4aacd646233fd5e851a5157f4ab2b6296f241214a99c9be8b77d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
